inherit_from: ../../.rubocop.yml

# Entries below are temporary while we work to enable or reconfigure them

Metrics/AbcSize:
  Exclude:
    - lib/edit_me/extension.rb
    - lib/open_in_widget/extension.rb
    - lib/elastic_compat_tree_processor/extension.rb
    - lib/alternative_language_lookup/extension.rb
    - lib/alternative_language_lookup/alternative.rb
    - lib/alternative_language_lookup/listing.rb

Metrics/MethodLength:
  Exclude:
    - spec/spec_helper.rb
    - lib/edit_me/extension.rb
    - lib/open_in_widget/extension.rb
    - lib/copy_images/extension.rb
    - lib/copy_images/copier.rb
    - lib/elastic_compat_preprocessor/extension.rb
    - lib/alternative_language_lookup/alternative.rb
    - lib/alternative_language_lookup/extension.rb
    - lib/alternative_language_lookup/listing.rb
    - lib/elastic_include_tagged/extension.rb
